# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# data reset
StopLine.destroy_all
StarredStop.destroy_all
Stop.destroy_all
Line.destroy_all
User.destroy_all

########################## parser

file = File.open("./public/stops.txt")
file_data = file.readlines # reads data from stops.txt

$stops = file_data.map do |line|
  line.split(',,') # splits string by duble commas
end

file.close

def parse_stops
  $stops.map do |text_line|
    Stop.create(stop_id: text_line[0], name: text_line[1]) # [0] stop id, [1] stop name
  end
end

parse_stops

Line.create(name: "7", feed_id: 51)
Line.create(name: "J", feed_id: 36)
Line.create(name: "Z", feed_id: 36)
Line.create(name: "G", feed_id: 31)
Line.create(name: "B", feed_id: 21)
Line.create(name: "D", feed_id: 21)
Line.create(name: "F", feed_id: 21)
Line.create(name: "M", feed_id: 21)
Line.create(name: "N", feed_id: 16)
Line.create(name: "Q", feed_id: 16)
Line.create(name: "R", feed_id: 16)
Line.create(name: "W", feed_id: 16)
Line.create(name: "A", feed_id: 26)
Line.create(name: "C", feed_id: 26)
Line.create(name: "E", feed_id: 26)
Line.create(name: "S (Franklin Ave Shuttle)", feed_id: 26)
Line.create(name: "1", feed_id: 1)
Line.create(name: "2", feed_id: 1)
Line.create(name: "3", feed_id: 1)
Line.create(name: "4", feed_id: 1)
Line.create(name: "5", feed_id: 1)
Line.create(name: "6", feed_id: 1)
Line.create(name: "S", feed_id: 1)
Line.create(name: "L", feed_id: 2)

# 7 Line
StopLine.create(stop_id: Stop.find_by(stop_id: "726").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "725").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "724").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "723").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "721").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "720").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "719").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "718").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "716").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "714").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "713").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "712").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "711").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "710").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "709").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "708").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "707").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "706").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "705").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "702").id, line_id: Line.find_by(name: "7").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "701").id, line_id: Line.find_by(name: "7").id)

# J Line
StopLine.create(stop_id: Stop.find_by(stop_id: "M23").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "M22").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "M21").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "M20").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "M19").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "M18").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "M16").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "M14").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "M13").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "M12").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "M11").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J31").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J30").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J29").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J28").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J27").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J24").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J23").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J22").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J21").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J20").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J19").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J17").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J16").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J15").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J14").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J13").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J12").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G06").id, line_id: Line.find_by(name: "J").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G05").id, line_id: Line.find_by(name: "J").id)

# Z line
StopLine.create(stop_id: Stop.find_by(stop_id: "M23").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "M22").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "M21").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "M20").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "M19").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "M18").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "M16").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J30").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J28").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J27").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J24").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J23").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J21").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J20").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J17").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J15").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J14").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "J12").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G06").id, line_id: Line.find_by(name: "Z").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G05").id, line_id: Line.find_by(name: "Z").id)

# L line
StopLine.create(stop_id: Stop.find_by(stop_id: "L01").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L02").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L03").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L06").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L08").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L10").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L11").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L12").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L13").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L14").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L15").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L16").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L17").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L19").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L20").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L21").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L22").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L24").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L25").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L26").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L27").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L28").id, line_id: Line.find_by(name: "L").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "L29").id, line_id: Line.find_by(name: "L").id)

# G line
StopLine.create(stop_id: Stop.find_by(stop_id: "G22").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G24").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G26").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G28").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G29").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G30").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G31").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G32").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G33").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G34").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G35").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G36").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A42").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "F20").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "F21").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "F21").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "F23").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "F24").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "F25").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "F26").id, line_id: Line.find_by(name: "G").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "F27").id, line_id: Line.find_by(name: "G").id)

# N line
StopLine.create(stop_id: Stop.find_by(stop_id: "R01").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R03").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R04").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R05").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R06").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R08").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R09").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R11").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R13").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R14").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R15").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R16").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R17").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R18").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R19").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R20").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R21").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R22").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R23").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R24").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R25").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R26").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R27").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R28").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R29").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R30").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R31").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R32").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R33").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R34").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R35").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R36").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R39").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R40").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R41").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "N02").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "N03").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "N05").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "N06").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "N07").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "N08").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "N09").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "N10").id, line_id: Line.find_by(name: "N").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "N12").id, line_id: Line.find_by(name: "N").id)

# Q line
StopLine.create(stop_id: Stop.find_by(stop_id: "D43").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "D42").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "D41").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "D40").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "D39").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "D34").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "D33").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "D32").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "D31").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "D30").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "D29").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "D28").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "D27").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "D26").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R41").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R31").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R30").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R22").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R21").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R20").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R19").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R18").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R17").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R16").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R15").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R14").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R11").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "Q03").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "Q04").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "Q05").id, line_id: Line.find_by(name: "Q").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "Q01").id, line_id: Line.find_by(name: "Q").id)

# R line
StopLine.create(stop_id: Stop.find_by(stop_id: "G08").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G09").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G10").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G11").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G12").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G13").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G14").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G15").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G16").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G18").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G19").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G21").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R13").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R45").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R44").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R14").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R31").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R30").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R22").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R21").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R20").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R19").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R18").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R17").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R16").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R15").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R14").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R11").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "Q04").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "Q05").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R42").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R40").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R39").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R36").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R35").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R34").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R33").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R32").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R29").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R28").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R27").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R26").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R23").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R24").id, line_id: Line.find_by(name: "R").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "R25").id, line_id: Line.find_by(name: "R").id)

# A line
StopLine.create(stop_id: Stop.find_by(stop_id: "A02").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A03").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A05").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A06").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A07").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A09").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A10").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A11").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A12").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A14").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A15").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A16").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A17").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A18").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A19").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A21").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A22").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A24").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A25").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A27").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A28").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A30").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A31").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A32").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A33").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A34").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A36").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A38").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A40").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A41").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A42").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A43").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A44").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A45").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A46").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A47").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A48").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A49").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A50").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A51").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A52").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A53").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A54").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A55").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A57").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A59").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A60").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A61").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A63").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A64").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A65").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "H01").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "H02").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "H03").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "H04").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "H06").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "H07").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "H08").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "H09").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "H10").id, line_id: Line.find_by(name: "A").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "H11").id, line_id: Line.find_by(name: "A").id)

# E line

StopLine.create(stop_id: Stop.find_by(stop_id: "G05").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G06").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G07").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "F05").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "F06").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "F07").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G08").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G09").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G10").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G11").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G12").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G13").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G14").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G15").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G16").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G18").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G19").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G20").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "G21").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "F09").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "F11").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "F12").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "D14").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A25").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A27").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A28").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A30").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A31").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A32").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A33").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A34").id, line_id: Line.find_by(name: "E").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "E01").id, line_id: Line.find_by(name: "E").id)

# C line
StopLine.create(stop_id: Stop.find_by(stop_id: "A09").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A10").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A11").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A12").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A14").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A15").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A16").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A17").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A18").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A19").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A20").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A21").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A22").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A24").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A25").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A27").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A28").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A30").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A31").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A32").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A33").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A34").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A36").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A38").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A40").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A41").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A42").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A43").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A44").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A45").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A46").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A47").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A48").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A49").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A50").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A51").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A52").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A53").id, line_id: Line.find_by(name: "C").id)
StopLine.create(stop_id: Stop.find_by(stop_id: "A54").id, line_id: Line.find_by(name: "C").id)

User.create(username: "Eric", password: "abc123")

puts "DONE!"
